### ISSUE TITLE
test is not working

### ISSUE THREAD

**Issue by arademaker** [racket-tw/k#13]
test.rkt example is not working. Maybe related to #8 

```
; /Users/ar/work/k/example/test.rkt:6:31: x: unbound identifier
;   in: x
; Context (plain; to see better errortrace context, re-run with C-u prefix):
;   /Users/ar/work/k/core.rkt:58:0 check-type
;   .../parse/define.rkt:20:4
;   /Users/ar/.emacs.d/elpa/racket-mode-20210727.1545/racket/syntax.rkt:66:0
```

Do you have more documentation about the package?

**Comment by dannypsnl** [comment]
Yes, since I just change the encoding yesterday, that one is broken as expected. The problem is we haven't implement Pi-type dependencies correctly. About documentation, this is an actively developing project, but I can add some recently once `eq-trans`, `eq-symm`, and several usual proofs about `Nat` works.

**Comment by arademaker** [comment]
Nice! Are you aware of https://european-lisp-symposium.org/static/2017/peschanski.pdf? 

Nice to see a racket implementation.

**Comment by dannypsnl** [comment]
I never see that before, thanks. I hope eventually this implementation can bring CubicalTT to racket XD.

**Comment by dannypsnl** [comment]
Doc: https://docs.racket-lang.org/k/index.html

close, feel free to reopen.
